Repository pydantic/pydantic-ai, pull requests merged in 2024-12, with the labels that each got.

#159 Minor docs updates
  pydantic_ai_slim/pydantic_ai/agent.py
  pydantic_ai_slim/pydantic_ai/messages.py
Labels: documentation

#212 Documentation: minor spelling and phrasing fixes
  docs/api/models/ollama.md
  docs/results.md
  tests/test_examples.py
Labels: documentation

#214 Add note about jupyter workaround for conflicting event loops
  docs/agents.md
  docs/index.md
  tests/test_examples.py
Labels: documentation

#217 Standardize "py" -> "python" in code blocks with pre-commit
  README.md
  docs/agents.md
  docs/api/models/ollama.md
  docs/api/models/vertexai.md
  docs/dependencies.md
  docs/examples/bank-support.md
  docs/examples/chat-app.md
  docs/examples/pydantic-model.md
  docs/examples/rag.md
  docs/examples/sql-gen.md
  docs/examples/stream-markdown.md
  docs/examples/stream-whales.md
  docs/examples/weather-agent.md
  docs/index.md
  docs/install.md
  docs/logfire.md
  docs/message-history.md
  docs/results.md
  docs/testing-evals.md
  pydantic_ai_slim/pydantic_ai/_utils.py
  pydantic_ai_slim/pydantic_ai/agent.py
  pydantic_ai_slim/pydantic_ai/tools.py
Labels: documentation

#193 Add Anthropic (non-streaming) Support
  .github/workflows/ci.yml
  README.md
  docs/api/models/anthropic.md
  docs/index.md
  docs/install.md
  mkdocs.yml
  pydantic_ai_examples/pyproject.toml
  pydantic_ai_slim/pydantic_ai/_utils.py
  pydantic_ai_slim/pydantic_ai/messages.py
  pydantic_ai_slim/pydantic_ai/models/__init__.py
  pydantic_ai_slim/pydantic_ai/models/anthropic.py
  pydantic_ai_slim/pydantic_ai/models/groq.py
  pydantic_ai_slim/pydantic_ai/models/openai.py
  pydantic_ai_slim/pyproject.toml
  pyproject.toml
  tests/models/test_anthropic.py
  tests/models/test_model_function.py
  tests/test_live.py
  uv.lock
Labels: new models

#223 Add support for new Gemini model 'gemini-2.0-flash-exp'
  pydantic_ai_slim/pydantic_ai/models/__init__.py
  pydantic_ai_slim/pydantic_ai/models/gemini.py
Labels: new models

#276 Documentation: add grids, tables to make intro info easier to digest
  README.md
  docs/agents.md
  docs/extra/tweaks.css
  docs/index.md
  docs/overrides/.icons/logfire/logo.svg
  mkdocs.insiders.yml
  mkdocs.yml
Labels: documentation

#506 docs: fix typo in pydantic link for /api/models/gemini/
  docs/api/models/gemini.md
Labels: documentation

#518 Fix typo in type checking note
  docs/agents.md
Labels: documentation

#507 Reorganize examples
  .gitignore
  docs/.hooks/main.py
  docs/examples/bank-support.md
  docs/examples/chat-app.md
  docs/examples/pydantic-model.md
  docs/examples/rag.md
  docs/examples/sql-gen.md
  docs/examples/stream-markdown.md
  docs/examples/stream-whales.md
  docs/examples/weather-agent.md
  examples/README.md
  examples/pydantic_ai_examples/__main__.py
  examples/pydantic_ai_examples/bank_support.py
  examples/pydantic_ai_examples/chat_app.html
  examples/pydantic_ai_examples/chat_app.py
  examples/pydantic_ai_examples/chat_app.ts
  examples/pydantic_ai_examples/pydantic_model.py
  examples/pydantic_ai_examples/rag.py
  examples/pydantic_ai_examples/roulette_wheel.py
  examples/pydantic_ai_examples/sql_gen.py
  examples/pydantic_ai_examples/stream_markdown.py
  examples/pydantic_ai_examples/stream_whales.py
  examples/pydantic_ai_examples/weather_agent.py
  examples/pyproject.toml
  mkdocs.yml
  pyproject.toml
  tests/import_examples.py
  uprev.py
  uv.lock
Labels: documentation, examples

#549 fix icons?
  mkdocs.insiders.yml
  mkdocs.yml
Labels: documentation
