Repository pydantic/pydantic-ai, pull requests merged in 2025-01, with the labels that each got.

#588 Docs fix - remove unnecessary line in multi agent docs
  docs/multi-agent-applications.md
Labels: documentation

#590 Docs fix - change to pydantic-ai.git on contributing page
  docs/contributing.md
Labels: documentation

#641 fix: typo
  docs/results.md
Labels: documentation

#230 Add Gradio Demo for weather agent example
  docs/examples/weather-agent.md
  examples/pydantic_ai_examples/weather_agent_gradio.py
  examples/pyproject.toml
  pyproject.toml
  uv.lock
Labels: documentation

#644 Docs: fix freeze frame for gradio demo video
  docs/examples/weather-agent.md
Labels: documentation

#702 Fixed Typo in Question Graph Sub Command
  examples/pydantic_ai_examples/question_graph.py
Labels: documentation

#716 Implements Support to Control Direction of State Diagram Generated by Mermaid Code
  docs/graph.md
  pydantic_graph/pydantic_graph/graph.py
  pydantic_graph/pydantic_graph/mermaid.py
  tests/graph/test_mermaid.py
Labels: enhancement, graph, awaiting author revision

#753 Fix; f-string syntax error
  docs/.hooks/algolia.py
  docs/.hooks/build_llms_txt.py
Labels: documentation

#759 Update index.md
  docs/index.md
Labels: documentation

#757 Add codespell support (config, workflow to detect/not fix) and make it fix few typos
  .pre-commit-config.yaml
  docs/graph.md
  docs/tools.md
  pydantic_ai_slim/pydantic_ai/models/mistral.py
  pydantic_ai_slim/pydantic_ai/models/ollama.py
  pyproject.toml
  tests/typed_graph.py
Labels: documentation

#692 Ensure custom args are used when retried
  pydantic_ai_slim/pydantic_ai/models/test.py
  tests/models/test_model_test.py
Labels: awaiting author revision

#776 Update Function tools docs with usage of `docstring_format` and `require_parameter_descriptions`
  docs/tools.md
Labels: documentation

#786 added documentation to visualize a graph within a jupyter-notebook
  docs/graph.md
Labels: documentation

#810 Add `Cohere` docs and additional (live) tests
  .github/workflows/ci.yml
  docs/api/models/cohere.md
  docs/install.md
  docs/models.md
  mkdocs.yml
  pydantic_ai_slim/pydantic_ai/models/cohere.py
  tests/models/test_model.py
  tests/test_live.py
Labels: documentation

#809 Various docs improvements
  docs/index.md
  docs/logfire.md
  docs/message-history.md
  docs/troubleshooting.md
  pydantic_ai_slim/pydantic_ai/settings.py
  tests/test_examples.py
Labels: documentation

#811 Adding new gemini experimental models
  pydantic_ai_slim/pydantic_ai/models/__init__.py
  pydantic_ai_slim/pydantic_ai/models/gemini.py
Labels: new models
