Repository pydantic/pydantic-ai, pull requests merged in 2025-02, with the labels that each got.

#771 Weather Agent Sample: Only include tool_call_id to chatbot.append if it's set
  examples/pydantic_ai_examples/weather_agent_gradio.py
Labels: awaiting author revision

#852 fix error in evals example
  docs/testing-evals.md
Labels: documentation

#853 Add o3 support for OpenAIModel
  pydantic_ai_slim/pydantic_ai/models/__init__.py
  pydantic_ai_slim/pyproject.toml
  tests/models/test_model_names.py
  uv.lock
Labels: new models

#868 Update bank_support.py
  examples/pydantic_ai_examples/bank_support.py
Labels: documentation

#870 Enhancing httpx instrumentation docs
  docs/img/logfire-with-httpx.png
  docs/img/logfire-without-httpx.png
  docs/logfire.md
Labels: documentation

#923 Upgrade and pin `esbuild` dep in `docs-site`
  docs-site/package-lock.json
  docs-site/package.json
Labels: documentation

#924 Fix cookie dependency in `docs-site`
  docs-site/package-lock.json
  docs-site/package.json
Labels: documentation

#930 Add perplexity docs to OpenAI compatible models section
  docs/models.md
Labels: documentation

#986 Only run documentation build hooks in CI
  docs/.hooks/algolia.py
  docs/.hooks/build_llms_txt.py
Labels: documentation
